export const experienceCss = `
.ly-experience{padding:48px clamp(20px,5vw,80px);background:var(--dsw-alias-bg-base);scroll-behavior:auto}
.ly-experience>header{max-width:1100px;margin:auto;padding-bottom:16px;border-bottom:1px solid #c8cdc0}
.ly-experience>header small{letter-spacing:.16em;color:#68776c}.ly-experience h1{font:clamp(32px,4vw,48px)/1.4 'Songti SC','STSong','SimSun',serif;font-weight:500;letter-spacing:.1em;margin:12px 0}.ly-experience>header p{font-size:20px;margin:8px 0;color:#68776c}
.ly-journey-toolbar{display:flex;align-items:center;justify-content:space-between;gap:16px;margin:24px auto;max-width:1100px;font-size:16px;color:#64776c}
.ly-journey-toolbar select{font:inherit;min-height:44px;color:inherit;background:transparent;border:0;border-bottom:1px solid #a7b5a7;margin-left:8px;max-width:150px}.ly-experience button{border-radius:3px;box-shadow:none}.ly-time-nav{position:sticky;top:0;background:var(--dsw-alias-bg-base);z-index:2;display:flex;flex-wrap:wrap;gap:6px;border-bottom:1px solid #c8cdc0;padding:8px 0}.ly-time-nav>*{flex:none;white-space:nowrap}.ly-time-nav button{font-size:16px;min-height:44px;border:0;border-bottom:2px solid transparent;background:transparent}.ly-time-nav button[aria-current]{border-color:#436d63}.ly-time-nav small{font-size:12px}
.ly-journey{width:100%;max-width:1100px;margin:auto;position:relative}.ly-experience .ly-journey svg{width:100%;height:auto;max-height:none;display:block;overflow:visible}.ly-bank{fill:none;stroke:#dde4d4;stroke-width:96;stroke-linecap:round}.ly-water{fill:none;stroke:url(#ly-water);stroke-width:70;stroke-linecap:round}.ly-current{fill:none;stroke:#d3e5d7;stroke-width:2;stroke-dasharray:30 100;stroke-linecap:round;animation:ly-flow 15s linear infinite;opacity:.65}.ly-current-bank{stroke-width:1;stroke-dasharray:60 160;animation-duration:26s;opacity:.35}.ly-current-inner{stroke-width:16;stroke-dasharray:1 210;animation-duration:24s;opacity:.15}.ly-interval{fill:none;stroke:#b89457;stroke-width:82;opacity:.22;pointer-events:none}.ly-stem{stroke:#758c70;stroke-width:1.4;fill:none}.ly-stone{fill:#456d61;stroke:#eef1dc;stroke-width:2}.ly-stone-uncertain{fill:#8f7952;stroke-dasharray:3 2}.ly-journey g[role=button]{cursor:pointer;outline:none}.ly-journey g[role=button]:focus-visible .ly-stone{stroke:#1b443b;stroke-width:5}.ly-journey g[role=button]:hover .ly-stone{fill:#203f38}.ly-bank-caption{font-size:19px;line-height:1.65;color:var(--dsw-alias-label-primary)}.ly-bank-caption small{font-size:15px;letter-spacing:.04em;color:#5c766b}.ly-bank-caption p{margin:4px 0;display:-webkit-box;-webkit-line-clamp:3;-webkit-box-orient:vertical;overflow:hidden}.ly-bank-caption[data-side='-1']{text-align:right}.ly-river-key{font-size:15px;color:#68776c;margin:24px auto}
.ly-bay{max-width:1100px;margin:64px auto;padding:40px 0;border-top:1px solid #c8cdc0;background:radial-gradient(ellipse at center,#e0e9dc66,transparent 70%)}.ly-bay h2{font:36px/1.5 'Songti SC','SimSun',serif;letter-spacing:.12em}.ly-bay>p,.ly-bay>small{color:#637569}.ly-bay-leaves{display:flex;gap:30px;flex-wrap:wrap;padding:32px 0}.ly-bay-leaves button{max-width:290px;min-height:130px;border:0;border-bottom:2px solid #93a28a;border-radius:40% 3px 35% 3px;padding:28px 32px;text-align:left;background:#e5e9da;animation:ly-drift 14s ease-in-out infinite alternate}.ly-bay-leaves span{display:block;font-size:14px;color:#586e60;margin-top:16px}.ly-access-list{padding:0;list-style:none;max-width:760px;margin:24px auto}.ly-access-list li{border-bottom:1px solid #c8cdc0}.ly-access-list button{border:0;background:transparent;text-align:left;width:100%;padding:18px 0}
.ly-experience .ly-detail{max-width:760px;margin:40px auto;border:0}.ly-detail h2{font:32px/1.7 'Songti SC','SimSun',serif}.ly-experience .ly-book{max-width:740px;margin:36px auto;border:0}.ly-book-contents{display:flex;flex-wrap:wrap;gap:16px;padding:24px 0;border-bottom:1px solid #c8cdc0}.ly-book-contents a{min-height:44px;display:inline-flex;align-items:center}.ly-book-contents strong{width:100%;font-size:18px}.ly-book article>section{margin:48px 0;scroll-margin-top:32px}.ly-book article h3{font:30px/1.6 'Songti SC','SimSun',serif}.ly-book article p{font:22px/2 'Songti SC','SimSun',serif;text-indent:2em;max-width:36em}.ly-persona-result{border-block:1px solid #c8cdc0;padding:24px 0;margin:36px 0}.ly-persona-result>section{margin:24px 0}.ly-persona-result h3{font-size:19px;font-weight:600}.ly-persona-result p{margin:8px 0}.ly-persona-result details{font-size:16px}
.ly-tributary-root{fill:none;stroke:#729e91;stroke-width:12;stroke-linecap:round;opacity:.65}.ly-tributary{fill:none;stroke:#68978a;stroke-width:5;stroke-linecap:round;stroke-dasharray:1;stroke-dashoffset:0;animation:ly-branch-open .32s ease-out}.ly-visual-group{stroke-dasharray: .025 .025;stroke-width:3}.ly-tree-leaf{animation:ly-leaf-open .35s ease-out}.ly-tree-caption{text-align:center;font-size:16px;line-height:1.5;color:#334f45}.ly-tree-caption small{display:block;font-size:14px;color:#876f48}.ly-tree-caption span{display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}.ly-tree-control{font-size:15px;fill:#375e51;text-decoration:underline}.ly-crosslink{fill:none;stroke:#aa8150;stroke-width:2;stroke-dasharray:7 7;pointer-events:none}.ly-relation-label{font-size:13px;fill:#775935}.ly-experience .ly-grove{max-height:none;height:auto;display:block;overflow:visible}.ly-story-forest g[role=button]{cursor:pointer}.ly-story-forest g[role=button]:focus-visible{outline:3px solid #b89457;outline-offset:5px}.ly-bay{overflow:hidden}
@keyframes ly-branch-open{from{stroke-dashoffset:1}to{stroke-dashoffset:0}}@keyframes ly-leaf-open{from{opacity:0}to{opacity:1}}
@keyframes ly-flow{to{stroke-dashoffset:-520}}@keyframes ly-drift{from{box-shadow:0 3px 12px #587b6010}to{box-shadow:0 9px 22px #587b6020}}
@media(max-width:650px){.ly-experience{padding:24px 16px}.ly-journey-toolbar{align-items:center;flex-direction:row;font-size:14px;gap:8px;margin:16px 0}.ly-journey-toolbar button{white-space:nowrap;font-size:14px;padding:6px 10px}.ly-experience>header p{font-size:17px}.ly-experience>header small{font-size:13px}.ly-bank{stroke-width:58}.ly-water{stroke-width:40}.ly-interval{stroke-width:50}.ly-bank-caption{font-size:15px;line-height:1.5}.ly-bank-caption small{font-size:13px}.ly-bank-caption p{-webkit-line-clamp:4}.ly-bay-leaves{gap:18px}.ly-bay-leaves button{width:100%;max-width:none}.ly-experience .ly-detail{scroll-margin-top:16px}.ly-book article p{font-size:20px}.ly-time-nav{flex-wrap:nowrap;overflow-x:auto}.ly-time-nav button{white-space:nowrap}}

/* RC5 editorial water and bank-side hierarchy. */
.ly-experience{scroll-padding-top:100px}.ly-time-nav{top:0;gap:20px;border:0;box-shadow:0 12px 18px var(--dsw-alias-bg-base);padding:4px 0;background:var(--dsw-alias-bg-base)}.ly-time-nav button{font-family:Georgia,serif;letter-spacing:.08em;padding:4px 14px;color:#718178}.ly-time-nav button[aria-current]{color:#335b4c;border-color:#a88751}.ly-time-nav small{display:block;font-size:20px;line-height:12px;letter-spacing:4px;color:#8ba294}.ly-time-nav a{font-size:15px;align-self:center}
.ly-journey{max-width:1240px;padding-top:50px}.ly-bank{stroke:#dae7d9;stroke-width:104;opacity:.5;filter:blur(5px)}.ly-water{stroke-width:78;opacity:.87}.ly-current{stroke:#eaf0dd;stroke-width:1.3;opacity:.32;stroke-dasharray:73 131 19 241 47 83 11 197;animation-duration:39s}.ly-current-1{stroke-width:2.8;opacity:.18;stroke-dasharray:127 257 31 93 57 311;animation-duration:53s}.ly-current-2{stroke-width:.8;opacity:.43;stroke-dasharray:41 187 13 301 97 139;animation-duration:67s}.ly-interval{stroke:#b9ac7a;stroke-width:86;opacity:.12;filter:blur(5px)}
.ly-tributary-root{stroke-width:11;opacity:.62}.ly-tributary{stroke:#80a696}.ly-visual-group{stroke-dasharray:.06 .025;opacity:.5}.ly-junction{fill:#f5f1e5;stroke:#719281;stroke-width:2}.ly-tree-root .ly-stone{stroke-width:3;fill:#315c4d}.ly-tree-leaf .ly-stone{fill:#7b9d82;stroke:#f5f3e7}.ly-node-selected .ly-stone{stroke:#ad8750;stroke-width:5;fill:#456d54}.ly-tree-caption{background:var(--dsw-alias-bg-base);padding:2px 6px;font:16px/1.6 'Songti SC','SimSun',serif}.ly-tree-caption small{color:#748776;font:13px/1.6 Georgia,serif}.ly-tree-root .ly-tree-caption small{color:#92744a}.ly-tree-control{font-size:14px;text-decoration:none}.ly-river-key{max-width:40em;text-align:center;line-height:1.8}.ly-bay{margin-top:28px;padding:24px 0 0}.ly-bay h2{margin:12px 0}.ly-bay>p{font-size:17px}.ly-book article h3{font-size:32px;letter-spacing:.06em}.ly-book article>section{margin:64px 0}.ly-book article details{font-size:16px;color:#6d7e71}.ly-book-contents a{border:0;font-size:17px}
@media(max-width:650px){.ly-journey{padding-top:36px}.ly-bank{stroke-width:56}.ly-water{stroke-width:38}.ly-current{stroke-width:.8;opacity:.22}.ly-interval{stroke-width:44}.ly-time-nav{gap:0;scrollbar-width:thin}.ly-time-nav button{padding:5px 10px;font-size:15px}.ly-tree-caption{font-size:15px}.ly-bay{margin-top:16px}.ly-time-nav a{font-size:14px}}

@media(min-width:651px){.ly-time-nav{float:left;width:82px;height:0;overflow:visible;display:flex;flex-direction:column;flex-wrap:nowrap;top:24px;box-shadow:none;background:transparent;gap:12px}.ly-time-nav button{text-align:left;padding:10px 6px;border-left:2px solid transparent;border-bottom:0}.ly-time-nav button[aria-current]{border-left-color:#a88751}.ly-time-nav a{padding:10px 0}.ly-journey{width:calc(100% - 100px);margin-left:100px}.ly-bay{margin-left:100px}.ly-time-nav small{letter-spacing:2px}.ly-bay svg{max-width:100%}}
@media(max-width:650px){.ly-time-nav{position:relative;box-shadow:none;top:auto}.ly-story-forest g[role=button]{scroll-margin-block:100px}}
.ly-tree-outline{opacity:.22;pointer-events:none}.ly-tree-outline .ly-tributary{animation:none}.ly-tree-caption{background:transparent;text-shadow:0 0 5px var(--dsw-alias-bg-base),0 0 10px var(--dsw-alias-bg-base)}
.ly-story-forest g[role=button]:focus-visible{outline:none}.ly-story-forest g[role=button]:focus-visible .ly-stone,.ly-story-forest g[role=button]:focus-visible .ly-junction{stroke:#ad8750;stroke-width:4}.ly-story-forest g[role=button]:focus-visible text{font-weight:600}
.ly-story-forest :focus-visible{outline:none}.ly-story-forest g[role=button]:focus-within .ly-stone{stroke:#ad8750;stroke-width:4}@media(max-width:650px){.ly-relation-label{display:none}}
@media(prefers-reduced-motion:reduce){.ly-experience *{animation:none!important;transition:none!important;scroll-behavior:auto!important}}
`;
